### PR TITLE
ci: fix environment variable references in system tests

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by cpcloud** [comment]
@tswast Is there any reason not to stick the service account JSON creds into a repo secret?

**Comment by cpcloud** [comment]
I guess the decryption would be the reason at the moment :)

**Comment by cpcloud** [comment]
Ok, there's an actual bug here! I'll fix it

**Review by tswast — APPROVED** [review]

**Comment by cpcloud** [comment]
@tswast You're right about the head sha bit. I misread the [`pull_request_target` docs](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request_target), `pull_request_target` events run against the base of the pull request.

**Comment by tswast** [comment]
Looks like it's working now. Thanks! https://github.com/ibis-project/ibis-bigquery/runs/4717044031?check_suite_focus=true

**Comment by tswast** [comment]
Working in PRs as well: https://github.com/ibis-project/ibis-bigquery/runs/4717105215?check_suite_focus=true

**Pull request merged**
