### PR TITLE
bug: substr fails to compile (#94)

### LINKED ISSUE #94: substr fails to compile
Using `substr` in an expression results in `AttributeError: 'NoneType' object has no attribute 'op'`.

### PR DESCRIPTION
**Pull request by seibs**
Closes #94.

### CODE REVIEW

**Comment by tswast** [comment]
Getting a test failure:

```
_____________________________ test_boolean_casting _____________________________

alltypes = BigQueryTable[table]
  name: ibis-gbq.testing.functional_alltypes
  schema:
    index : int64
    Unnamed_0 : int64
  ...4
    date_string_col : string
    string_col : string
    timestamp_col : timestamp
    year : int64
    month : int64

    def test_boolean_casting(alltypes):
        t = alltypes
        expr = t.groupby(k=t.string_col.nullif("1") == "9").count()
        result = expr.execute().set_index("k")
        count = result["count"]
>       assert count.loc[False] == 5840

tests/system/test_client.py:714: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../.local/lib/python3.8/site-packages/pandas/core/indexing.py:931: in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
../../../.local/lib/python3.8/site-packages/pandas/core/indexing.py:1163: in _getitem_axis
    self._validate_key(key, axis)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pandas.core.indexing._LocIndexer object at 0x7fc302f73c70>, key = False
axis = 0

    @doc(_LocationIndexer._validate_key)
    def _validate_key(self, key, axis: int):
        # valid for a collection of labels (we check their presence later)
        # slice of labels (where start-end in labels)
        # slice of integers (only if in the labels)
        # boolean not in slice and with boolean index
        if isinstance(key, bool) and not is_bool_dtype(self.obj.index):
>           raise KeyError(
                f"{key}: boolean label can not be used without a boolean index"
            )
E           KeyError: 'False: boolean label can not be used without a boolean index'

../../../.local/lib/python3.8/site-packages/pandas/core/indexing.py:972: KeyError
=============================== warnings summary ===============================
```

Not 100% sure if it's related.

**Comment by tswast** [comment]
I think it's just a breaking change in pandas. Probably need to update that test.

**Comment by seibs** [comment]
I'm also seeing this error in the CI output. Locally I ran against Ibis 1.2, but looks like maybe the CI is running against 2.0?

```
ibis_bigquery/client.py:24: in <module>
12
    from ibis.client import Database, Query, SQLClient
13
E   ModuleNotFoundError: No module named 'ibis.client'
14
Error: Process completed with exit code 4.
```

**Review by tswast — APPROVED** [review]
Thanks for the contribution!

**Comment by tswast** [comment]
> I'm also seeing this error in the CI output. Locally I ran against Ibis 1.2, but looks like maybe the CI is running against 2.0?

That's correct. I've just updated it to only run against 1.x on the v1 branch. Work is still in progress to support Ibis 2.x.

**Pull request merged**
